[package]
name = "multi_party_ecdsa"
version = "0.1.0"
authors = [
    "Gary <gary@kzencorp.com>"
]

[lib]
name = "multi_party_ecdsa"
crate-type = ["dylib"]

[dependencies]
cryptography-utils = { git = "https://github.com/KZen-networks/cryptography-utils" }

